### PR TITLE
adding a corrected butane xyz

### PR DESCRIPTION
**Pull request by amandadumi**
Actually, the butane.xyz is only used to test importation of an xyz file and NotImplemented areas, thus no tests have to change. It makes sense why we haven't noticed the issue until now...

### CODE REVIEW

**Comment by amandadumi** [comment]
Since it is now only the file changing, I can just make this change with the connectivity test if anyone prefers.

**Comment by dlf57** [comment]
I'm fine with either changing it now or adding into connectivity PR. That's great we didn't have the issue in the other files!

**Comment by amandadumi** [comment]
yeah...I may or may not have wasted some time before realizing they were built from the butane sdf and not the xyz. I will just place it in one commit then with a note of the change.

**Comment by shivupa** [comment]
Yeah I'd be fine either way. If we have it as a separate PR like this then can we update a test so both the xyz and sdf path is tested?

**Comment by amandadumi** [comment]
The path is already tested, but it wasn't dependent on the input of the file. So we still had 100% coverage at this point. The contents will be important once I have the connectivity pushed, so I think it's fine to do it in one.

**Pull request closed without merging**
