### PR TITLE
Fix Docs

### PR DESCRIPTION
**Pull request by shivupa**
Opening PR to see if PR build for docs trigger
See here: https://docs.readthedocs.io/en/latest/guides/autobuild-docs-for-pull-requests.html

### CODE REVIEW

**Comment by dlf57** [comment]
https://docs.readthedocs.io/en/latest/guides/autobuild-docs-for-pull-requests.html#troubleshooting 
I think we might need to authorize read the docs on for the repo/org and change the settings

**Comment by shivupa** [comment]
Yeah I think I did that but it seems like it still didn't trigger

**Comment by dlf57** [comment]
Yeah this is weird that it won't trigger

**Comment by shivupa** [comment]
OH there it is!

**Comment by shivupa** [comment]
Yay! I'm very excited this should make sorting RTD stuff out a lot easier

**Comment by dlf57** [comment]
Awesome! I hadn't thought of just closing it and reopening it to trigger it!

**Comment by shivupa** [comment]
I wasn't sure it was going to work, but I'm glad it did!

**Comment by dlf57** [comment]
IT WORKS!!!!

**Comment by dlf57** [comment]
The API info still does not show up unfortunately

**Comment by shivupa** [comment]
Yup I want to fix that then this should be good to go!

**Comment by shivupa** [comment]
Ok this is ready for review. If anyone has any suggested changes let me know!

**Pull request merged**
