### PR TITLE
Update BAT to use DFS for angles and torsions

### PR DESCRIPTION
**Pull request by dlf57**
I updated BAT to use a depth-first search for angles and torsions as the previous method was messy and it looks like occasionally might have missed a torsion. It should be a lot cleaner and catching all angles and torsions now. 

The test file doesn't look the best, if there are any recommendations on how to format it better please let me know.

### CODE REVIEW

**Comment by dlf57** [comment]
It looks like scipy might be a dependency of cclib and isn't getting installed when cclib is so I believe we are going to need to add it as a dependency for the repo.

**Comment by shivupa** [comment]
> It looks like scipy might be a dependency of cclib and isn't getting installed when cclib is so I believe we are going to need to add it as a dependency for the repo.

Yeah cclib/cclib#970 should have fixed it upstream, but that hasn't made it into a release.

**Comment by shivupa** [comment]
This sounds interesting. I'll give it a look this weekend!

**Review by shivupa — APPROVED** [review]
I'm assuming the test diff is just it getting formatted. That is what it looks like. I am fine with this

**Comment by shivupa** [comment]
This looks correct and tests are green

**Comment by dlf57** [comment]
Did you want me to leave scipy as a requirement?

**Comment by shivupa** [comment]
I don't see a problem with it. It is common enough and fixes the issue. The only other choice would be to make the required cclib version the newest (forthcoming) release. I think it would be better to have the scipy dependency and be able to use older cclib versions

**Comment by dlf57** [comment]
Okay! I'll edit the README to show it as a requirement and clean everything up in to one commit either tonight or tomorrow.

**Comment by amandadumi** [comment]
This is really great! Thanks for implementing this. The formatting of the test file has been a question for us all from the start. Even if it looks messy, as long as we're sticking with the same format style, I think this is more maintainable.

Once the README is updated, I will merge.

**Comment by dlf57** [comment]
Everything should be cleaned up now! Let me know if there's anything else I need to do before this gets merged!

**Review by amandadumi — APPROVED** [review]
This looks great!

**Pull request merged**
